class LetError {
	func():Int {
		let a:Int, b:, c:Int<-3, d <- 4 in a+b+c+d
	}
}
